feat: Bump Ubuntu version 25.04 -> 25.10.

diff --git a/src/base/.devcontainer/Dockerfile b/src/base/.devcontainer/Dockerfile
--- a/src/base/.devcontainer/Dockerfile
+++ b/src/base/.devcontainer/Dockerfile
@@ -1,14 +1,14 @@
-ARG VARIANT="plucky"
+ARG VARIANT="questing"
 FROM buildpack-deps:${VARIANT}-curl
 
 LABEL dev.containers.features="common"
 
 ARG VARIANT
-RUN if [ "$VARIANT" = "plucky" ]; then \
+RUN if [ "$VARIANT" = "questing" ]; then \
       if id "ubuntu" &>/dev/null; then \
-        echo "Deleting user 'ubuntu'  for $VARIANT" && userdel -f -r ubuntu || echo "Failed to delete ubuntu user for $VARIANT"; \  
+        echo "Deleting user 'ubuntu'  for $VARIANT" && userdel -f -r ubuntu || echo "Failed to delete ubuntu user for $VARIANT"; \
       else \
-        echo "User 'ubuntu' does not exist for $VARIANT"; \ 
+        echo "User 'ubuntu' does not exist for $VARIANT"; \
       fi; \
     fi
 
